### ISSUE TITLE
Broken list

### ISSUE THREAD

**Issue by haz** [AI-Planning/planutils#117]
Seems as though the short names are breaking the `planutils list` after being installed. Able to take a look at this @nilsjor ?

```bash
(planutils) root@8563898400e4:~$ planutils list
Installed            Summary
-------------------- ---------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/planutils/__init__.py", line 146, in main
    package_list()
  File "/usr/local/lib/python3.10/dist-packages/planutils/package_installation.py", line 119, in package_list
    print("%-*s %s" % (width_name, p, PACKAGES[p]['name']))
KeyError: 'fd'
(planutils) root@8563898400e4:~$
```

From a fresh `planutils` docker image, you can run the following to get the above:

```bash
$ planutils activate
$ planutils install lama-first
$ planutils list
```

Also, was part of #115 meant to remove the auto-run functionality? Usually, if a planner wasn't installed and you tried using it, it would prompt for installation. This is the current behaviour:

```bash
(planutils) root@8563898400e4:~$ lama-first
Package downward is not installed
(planutils) root@8563898400e4:~$
```

**Comment by nilsjor** [comment]
Will have a look

**Comment by nilsjor** [comment]
I will admit that the shortname-as-alias implementation has some issues. Sorry for that.

For the sake of the current release, perhaps you should revert 065d4ca732b74fa53b7aa67a696c8dec7458353a and 38c711be4771ee8e3cdfc29f6609617ba08338ea and release 0.9.1.
The other commits i submitted are independent of the shortname-feature!

I could submit another PR when I have tested it more rigorously. We could then have a discussion about the particular package names before you merge.

**Comment by nilsjor** [comment]
> Also, was part of #115 meant to remove the auto-run functionality? Usually, if a planner wasn't installed and you tried using it, it would prompt for installation. This is the current behaviour:
> 
> ```shell
> (planutils) root@8563898400e4:~$ lama-first
> Package downward is not installed
> (planutils) root@8563898400e4:~$
> ```

**I have found the reason for this!** As you know, when running `planutils activate`, the scripts for the short-hand invocation are written into `.planutils/bin`.

An example of these scripts is shown below (lama-first):
```
#!/bin/bash
if $(planutils check-installed lama-first)
then
  ~/.planutils/packages/lama-first/run $@
else
  echo
  echo 'Package not installed!'
  read -r -p "  Download & install? [Y/n] " varchoice
  varchoice=${varchoice,,}
  if ! [[ "$varchoice" =~ ^(no|n)$ ]]
  then
    if planutils install lama-first;
    then
      echo 'Successfully installed lama-first!'
      echo
      echo "Original command: lama-first $@"
      read -r -p "  Re-run command? [Y/n] " varchoice
      varchoice=${varchoice,,}
      if ! [[ "$varchoice" =~ ^(no|n)$ ]]
      then
        ~/.planutils/packages/lama-first/run $@
      fi
    fi
  fi
  echo
fi
```

**However**, it appears that the exit code for $(planutils check-installed <package>) is always 0! You can try this with 
```
$(planutils check-installed lama-first); echo $?
```

In the above script example, the result is that it will execute the `run`-file for lama-first, which is in turn to invoke downward.

If you instead try to run, for example
```
$ symk
```
you will see that it will also try to run the correpsonding `run-file:
```
FATAL:   could not open image /root/.planutils/packages/symk/symk.sif: failed to retrieve path for /root/.planutils/packages/symk/symk.sif: lstat /usr/local/lib/python3.10/dist-packages/planutils-0.9.0-py3.10.egg/planutils/packages/symk/symk.sif: no such file or directory
```

Looking at the functions for `check-installed`, we can see that the code is unchanged for the last three years. Perhaps some change in Python has caused this, but it do not believe it has anything to do with #115 at least.

**Comment by haz** [comment]
Looks like this all came about with this line:

https://github.com/AI-Planning/planutils/pull/115/files#diff-454e2c73bd60d11b64749ee6855487b99ca8eb4b7e6e726c9c5153505e2db868R26

It overrides the return code from the python call when the history is wiped. Did you mean to do that just after activation? Opened a PR at #120 to take a look.

**Comment by nilsjor** [comment]
Hey, nice catch. Indeed, the idea was just to clear the history after activate; I was using a custom "planutils-cli" image with the entrypoint "planutils activate" and it seemed strange that the activate script would appear in the history line-for-line (comments and all)...

I had a look at #120. It does not seem to clear the history. Instead, the line `history -cw` appears in the history as well 😖 

However, it seems the fix is as simple as removing the `-i` flag in the shebang. I have a commit on my fork (5804d673782eb44c293b37ff6bded9cda7c83874) which you could include in this PR if you want.

I have tested the above examples, as well as `list`, `show`, `install`, `run` etc.

**Comment by haz** [comment]
Hrmz...wouldn't the `-i` be required to use it interactively? Does it change behaviour either inside the activated environment or outside when running `planutils <command>` stuff? I won't have a chance to test til later today.

I don't believe that I'd include the `-i` by default, so there must have been some reason :P. The git blame doesn't reveal much...

**Comment by nilsjor** [comment]
> I don't believe that I'd include the `-i` by default, so there must have been some reason :P. The git blame doesn't reveal much...

I have discovered what it is good for! It ensures that the current directory appears as the shell prefix:
```sh
(planutils) root@47f41c451c32:~/domains$ planutils show lama
```
instead of just 
```sh
(planutils) planutils show lama
```

Some further digging -- it appears that the bin/planutils script only appears in the bash history if you activate _twice_. Which will happen for me since the base image Dockerfile looks like:
```
...

# Setup the planutils
RUN planutils setup

# default command to execute when container starts
CMD /bin/bash
```

and my "interactive" image looks like
```
FROM planutils:latest

RUN planutils install -f -y lpg-td
...
CMD planutils activate
```

Would it be a good idea to change the entrypoint for the base image so that it launches inside the activated planutils environment? 

Finally, I realize that the appearance of lines of code in the history is a minor issue, and it may not be worthwhile ;)

**Comment by haz** [comment]
> I have discovered what it is good for! It ensures that the current directory appears as the shell prefix:

Aha! A useful addition, I reckon.

We don't activate by default since there was significant indication that users _don't_ want that as a default (as much as I prefer it myself ;)). Maybe we could fill a bit of the bash history (upon activate) with some blank line echos so that it's clear when you hit the "start of history" time?
