### ISSUE TITLE
smtplan and others segfault on singularity run

### ISSUE THREAD

**Issue by aindilis** [AI-Planning/planutils#122]
Hi,

Thanks for making planutils available!

I'm running into a problem, it runs on one machine of mine, but does not run on the machine I need it to run on.

Whether I install aiplanning/planutils:latest or planutils-dev:latest, on my host ai2 (Deb 11, amd64, Linux 5.10.0-18-amd64) I get the following error when trying to run SMTPlan+ on any planning domain/problem (although it outputs help normally when run without any arguments).

```|/root/.planutils/packages/smtplan/run: line 3:   303 Segmentation fault      (core dumped) singularity run -e $(dirname $0)/smtplan.sif /SMTPlan $@```

If I install on a different host ai6 (Deb 11, amd64, 5.10.0-21-amd64) it runs okay. 
For various reasons I need it to run on ai2.  Therefore, I was hoping there is some obvious thing I'm missing, or that the error message makes sense to someone.

Thanks,

Andrew Dougherty

**Comment by aindilis** [comment]
Ah, it probably has to do with running a bind mount.  Closing, but leaving up for reference in case someone else runs into the problem. It seems to work with docker cp instead.

**Comment by aindilis** [comment]
Hi,

I thought I would reopen this issue, while simultaneously trying to route around it by implementing a wrapper that does `docker cp` to and from the docker FS. However, I do get that segfault whenever using a bind mount, with any planner. I can cat the PDDL files, so the planner can see them, so I'm not sure why it's segfaulting. 

I thought maybe it was a problem writing the output file, but I ran `touch file` and it worked, although on the host it was owned by root.

I am not proficient with Docker or Singularity so it's likely I'm doing something wrong. I'm including a link now to a wrapper I wrote for planutils to work with my legacy Verber planner wrapper:

https://frdcsa.org/~andrewdo/verber-planutils-wrapper.tgz

To replicate the issue, I first clone https://github.com/AI-Planning/planutils, then cd into it, then run:

`docker run -it --privileged --detach --mount type=bind,source=<HOSTDIR>,target=<GUESTDIR>`

Followed by determining the container id, and then:

`docker exec -it <CONTAINERID> bash`

`planutils activate
planutils install -y smtplan
smtplan <DOMAIN> <PROBLEM>`

And that should be sufficient to replicate the above error, which was:

`|/root/.planutils/packages/smtplan/run: line 3:   303 Segmentation fault      (core dumped) singularity run -e $(dirname $0)/smtplan.sif /SMTPlan $@`

Any help would be appreciated.

Thanks again!

Andrew

**Comment by aindilis** [comment]
Thank you for asking the right question - they were mounted such that there was possibly a dangling symlink from the docker file system's point of view. Strange that cat could see it, but the planners couldn't. By changing up the source and target mount points, and making changes to my wrapper to reflect that, it now works. Thanks!

**Comment by haz** [comment]
Glad it helped! Though, it's entirely a happy coincidence...many of these singularity wrapped planners need the files to be located in the home path of the container. That was my hunch, but it sounds like it helped you figure out the true issue anyways.
