### ISSUE TITLE
pyperplan package

### ISSUE THREAD

**Issue by haz** [AI-Planning/planutils#14]
Docker recipe that can be adapted:

```
#################################
# Download and Install Pyperplan
#################################
ENV PYPERPLAN_URL=https://github.com/aibasel/pyperplan/archive/master.tar.gz
RUN curl -SL $PYPERPLAN_URL | tar -xz \
        && mv pyperplan-* pyperplan
RUN echo 'alias pyperplan="python3 ${BASE_DIR}/pyperplan/src/pyperplan.py"' >> ~/.bashrc
```

**Comment by jendrikseipp** [comment]
Another option is to use `pip install pyperplan`.

**Comment by haz** [comment]
Far cleaner! But will we now have a conflict on the command-line between the planutils package and pip-installed version?

**Comment by jendrikseipp** [comment]
Yes, I guess there would be a conflict. I think the cleanest solution to issues like this is to switch from invocations like "lama" to "planutils run lama". This would also avoid having to alter the .bashrc file. 

By the way, maybe it's best to install pyperplan into a virtual environment. `pipx install pyperplan` does that auto automatically (notice the x at the end of pipx).

**Comment by haz** [comment]
I dislike having to always prefix things with `planutils run ...`, but am growing increasingly concerned at dumping the entire package list on the `PATH`...how about `planutils run ...` in addition to `planutils activate`? Then the docker can just come with planutils pre-activated.

Never seen `pipx` before...nice!

**Comment by jendrikseipp** [comment]
> how about `planutils run ...` in addition to `planutils activate`?

I guess you mean `planutils setup`? Yes, that could be a solution.

To clarify, I think it's fine to have `lama` available on the PATH after running `planutils install lama`, I just think it's too much magic to allow users to call `lama` to install and run it. I think it's easier to explain `planutils install lama` to users. This is also how pip, pipx, and apt work. To avoid messing with the PATH, you could also take the flatpak approach that I suggested above, i.e., `planutils run lama`. I guess it's a matter of taste.

**Comment by haz** [comment]
Well I meant for `planutils activate` to take you into the virtual planutils environment. At which point, it behaves like it currently does (so running lama without it being installed will prompt). Essentially just muck with the PATH variable on demand.

So I'd still need to muck w/ the `.bashrc` if we want `planutils install lama` to expose it in general. Could have two bin directories -- one with all the packages that is only on PATH when the planutils is activated and one that's permanently on PATH (for things installed).

Thoughts on that approach?

**Comment by jendrikseipp** [comment]
I like it :+1:

**Comment by haz** [comment]
So two followups:

1) Assuming we must `planutils activate` to get unfettered access to the planners, what does `pipx` further provide?
2) What would be the steps to equip `planutils` to be `pipx`-ready?

**Comment by jendrikseipp** [comment]
1. pipx is simply the recommended way of installing Python **applications**, whereas pip is the recommended way of installing Python **packages**. 
2. Actually, there are no extra steps needed. I just tried installing planutils with pip and it works:

```
$ pipx install planutils
  installed package planutils 0.2.7, Python 3.8.10
  These apps are now globally available
    - planutils
done! ✨ 🌟 ✨
```
Now `planutils` is on the PATH (because pipx adds ~/.local/bin to the PATH).
