### ISSUE TITLE
Non privileged docker

### ISSUE THREAD

**Issue by hectorpal** [AI-Planning/planutils#50]
> docker with the --privileged option

That requirement it's blocking my full use of planutils in heavily containerized contexts. 

Not all the tools here require that, but it's friction. 

It seems the solution would be to maintain both singularity and docker images. Right? I'd pay the price

**Comment by haz** [comment]
It's required for any of the software that uses singularity. So most :(.

If you have a modern Ubuntu host, then the non-docker version is about to become very much viable. Biggest hurdle to installing planutils natively was having the right version of singularity. That should be good to go now, and planutils is about to get a non-intrusive installation option that doesn't mess with you PATH var if you don't want it to.

**Comment by hectorpal** [comment]
Lovely. Thanks!

**Comment by haz** [comment]
Aye, you bet.
