### ISSUE TITLE
Lacks separation between "force" and "assume yes" option

### ISSUE THREAD

**Issue by guicho271828** [AI-Planning/planutils#53]
See that in `apt-get` and other package managers the semantics of user query and forced install are separated:

* "-y" / yes option --- assume all confirmations as "yes" for batch processing
* "-f" / force option --- force reinstalling the package for whatever reasons (e.g. for fixing a partially broken installation)

Currently, `install` command lacks this separation. It can choose to force the installation, but its true meaning is `yes`.

**Comment by haz** [comment]
Closed with #54
