### ISSUE TITLE
smtplan: remote has no library client

### ISSUE THREAD

**Issue by bhomaidan1990** [AI-Planning/planutils#90]
I'm using the Docker Image from the Docker Hub as mentioned [here](https://github.com/AI-Planning/planutils/issues/89#issue-1285896322), I tried to use the `smtplan` planner and I have got this error:
```sh
(planutils) root@104582ad0e5f:~$ smtplan 

Package not installed!
  Download & install? [Y/n] Y
smtplan will be installed.

About to install the following packages: smtplan (148M)
  Proceed? [Y/n] Y
Installing smtplan...
FATAL:   Unable to get library client configuration: remote has no library client

Error installing smtplan. Rolling back changes...
rm: cannot remove 'smtplan.sif': No such file or directory
```
This issue didn't appear with `optic` planner for example. can you please help me resolve this issue? thanks in advance.

**Comment by haz** [comment]
Ya, this is a known issue with where it's hosted. #86 is the place to follow along.
