### ISSUE TITLE
planutils development container

### ISSUE THREAD

**Issue by jdekarske** [AI-Planning/planutils#92]
While testing, I was confused why my changes weren't reflected by building the default Dockerfile. An additional Dockerfile with a `COPY` instruction rather than a pypi install would be helpful. Arguably, this could be a better default build because you are cutting out the pypi middleman.

Should this go in the "environments" directory?

This is different than #9 because it specifically focuses on planutils. I'm not sure what more is needed in the environment to cover #9

**Comment by haz** [comment]
Hrmz...an interesting thought. But I think it's intimately tied with the CI/CD that makes changing it not advisable.

https://github.com/AI-Planning/planutils/blob/main/.github/workflows/docker-image.yml

Idea is that upon release, we build+push to pypi, and then build+push to dockerhub. This way, the dockerhub version always has the latest version that you'd find in pypi. I guess we could put the dockerhub version somewhere else and use the top-level Dockerfile as an example?

**Comment by nilsjor** [comment]
I disagree, what you describe is not continuous integration, but some kind of "release-time integration". Any changes pushed to main should be tested in the container as part of the build automation.

I have submitted a pull request for changing the Dockerfile to build locally. This is the default behaviour I and anyone else cloning this repo would expect.

**Comment by haz** [comment]
Just coming back to these PR's -- any chance you'd be up for tackling the above, @nilsjor ?

**Comment by nilsjor** [comment]
Yes, I am on it. I will submit a new pull request for this feature.

[This PR request ](https://github.com/AI-Planning/planutils/pull/105#issue-1434842171) will be closed, and a new one submitted for adding "legacy" solvers.
