### ISSUE TITLE
`docker build` fails on Mac M1

### ISSUE THREAD

**Issue by victorpaleologue** [AI-Planning/planutils#93]
Trying to build the docker image with:
```sh
docker build -t planutils:latest .
```
I get the following error:
```
#6 2.523  27000K .......... .......... .......... .......... .......... 99% 14.1M 0s
#6 2.526  27050K ......                                                100%  276M=1.7s
#6 2.526 
#6 2.526 2022-07-05 15:15:43 (15.8 MB/s) - 'apptainer_1.0.2_amd64.deb' saved [27705364/27705364]
#6 2.526 
#6 2.538 dpkg: error processing archive apptainer_1.0.2_amd64.deb (--install):
#6 2.538  package architecture (amd64) does not match system (arm64)
#6 2.542 Errors were encountered while processing:
#6 2.542  apptainer_1.0.2_amd64.deb
------
executor failed running [/bin/sh -c wget https://github.com/apptainer/apptainer/releases/download/v1.0.2/apptainer_1.0.2_amd64.deb     && dpkg -i apptainer_1.0.2_amd64.deb     && rm apptainer_1.0.2_amd64.deb]: exit code: 1
Arrêt du processus de terminal "/bin/zsh '-c', 'docker build --pull --rm -f "Dockerfile" -t planutils:latest "."'". Code de sortie : 1.
```
I am working on a Mac M1, hence it works with arm64 instead of amd64.

**Comment by haz** [comment]
Any chance this could be a firewall issue?

**Comment by victorpaleologue** [comment]
I doubt it. I have no firewall configuration at least.
The .deb is properly downloaded, but the installation that fails because of the incompatible bytecode.
The error message says this: "dpkg: error processing archive apptainer_1.0.2_amd64.deb (--install):
#6 2.538  package architecture (amd64) does not match system (arm64) ».

**Comment by haz** [comment]
Seems to be a common / known issue with M1 devices (don't play nice with amd64). @FlorianPommerening -- you had the original recipe for Apptainer. Any chance we could have it revised to reflect the host machine architecture? Looks like amd64 is hardcoded atm.

**Comment by FlorianPommerening** [comment]
I have no Mac to test this on. If we can somehow detect the architecture within the Dockerfile, we could install another version. The trouble is that they do not offer an ARM release (https://github.com/apptainer/apptainer/releases/tag/v1.0.3). I guess that means, we have to build it from source. This is tricky without access to a test machine.

@victorpaleologue, can you try to install Apptainer from source (https://github.com/apptainer/apptainer/releases/download/v1.0.3/apptainer-1.0.3.tar.gz, https://github.com/apptainer/apptainer/blob/main/INSTALL.md) in a docker image?

**Comment by haz** [comment]
Couldn't use this?

https://archlinuxarm.org/packages/aarch64/apptainer

**Comment by victorpaleologue** [comment]
⬆️ here is my proposal, building on @FlorianPommerening 's idea.
The docker starts, but I did not try running the planner yet.

**Comment by victorpaleologue** [comment]
With the latest version of my PR https://github.com/AI-Planning/planutils/pull/94, it works.
Let me know what I should do next.

**Comment by FlorianPommerening** [comment]
> Couldn't use this?
> 
> https://archlinuxarm.org/packages/aarch64/apptainer

This is for arch. Is this compatible with the ubuntu base image we are using? If so, it is probably preferable to an installation from source. Let's move this discussion into #94. I think this issue is fixed no matter how we get apptainer installed, so we can discuss the implementation details in the pull request.

**Comment by psuzzi** [comment]
Same issue here, one year later.

**Comment by FlorianPommerening** [comment]
Sorry, this fell through the cracks so far. Is it still an issue? @psuzzi can you confirm that you are on the latest version and your build is using the new file `install-apptainer-ubuntu.sh`? Which part of it is failing? The script should recognize the architecture as different from `x86_64` and then install Apptainer from source.
