### ISSUE TITLE
using planutils from pip install rather than docker build

### ISSUE THREAD

**Issue by jan-dolejsi** [AI-Planning/planutils#95]
I am trying to _use_ planutils, rather than cloning it and building it first. The package appears to be pushed to https://pypi.org/project/planutils/. How do I use it from there? If I figured it out, I would like to update the `README.md` and then I would automate the setup by the VS Code extension.

Here is what I tried (and failed):

```
user@computer:~/c/github/vscode-pddl-samples$ pip install planutils
Collecting planutils
  Downloading planutils-0.7.6-py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 633 kB/s 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from planutils) (2.22.0)
Installing collected packages: planutils
Successfully installed planutils-0.7.6
user@computer:~/c/github/vscode-pddl-samples$ planutils activate
planutils: command not found
```

I am on Ubuntu 20.04 running as WSL on Windows.

**Comment by haz** [comment]
Very odd...it's meant to put `planutils` right on the path. Running `bash` to get a new shell do it?

**Comment by jan-dolejsi** [comment]
Yes, refresh helped. I closed the terminal meanwhile, but upon creating a new one, the activate works.
